name: nightly
on:
  schedule:
    # runs every day at 6am UTC
    - cron: "0 6 * * *"
  workflow_dispatch:

env:
  GO_VERSION: '1.21.1'

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup kubeconfig
        env:
          KUBECONFIG_FILE: ${{ secrets.KNUU_KUBECONFIG_FILE }}
        run: |
          mkdir -p $HOME/.kube
          echo "${KUBECONFIG_FILE}" > $HOME/.kube/config
      - name: Run e2e tests
        run: make test-e2e

  test-fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run fuzz tests
        run: make test-fuzz
