name: test
on:
  workflow_call:

env:
  GO_VERSION: '1.21.1'

jobs:
  test-short:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests in short mode
        run: make test-short
        timeout-minutes: 10

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests
        run: make test

  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Generate coverage.txt
        run: make test-coverage

      - name: Upload coverage.txt
        uses: codecov/codecov-action@v4.0.0
        with:
          file: ./coverage.txt

  test-race:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests in race mode
        run: make test-race
